server:
  port: 8761
eureka:
  client:
#  是否要注册到其他Eureka Server实例
    register-with-eureka: false
#    是否从其他Eureka Service实例获取数据
    fetch-registry: false
    service-url:
          defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true